#!/bin/bash

. "$HOME/.profile" # environment

[[ $- = *i* ]] || [[ $TERM = *xterm* ]] || return

# If this is not an ssh connection and NO_FISH isn't defined, replace!
if [ -z "$NO_FISH" ] && [ -z "$SSH_CONNECTION" ]; then
  echo "hi, normal terminal! replacing bash..."
  exec fish
fi

PS1='\u@\h \W $ '

echo "bourne again shell."
