[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 750
blink_timeout = 0
thickness = 0.05
unfocused_hollow = true
vi_mode_style = "None"

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "Jetbrains Mono"
style = "Light"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "Full"
dynamic_title = true
resize_increments = true
startup_mode = "Windowed"
decorations_theme_variant = "Dark"
opacity = 0.95
blur = true

[window.dimensions]
columns = 102
lines = 26

[window.padding]
x = 2
y = 2

[general]
live_config_reload = true
import = [
  "dark-theme.toml",
  #"light-theme.toml",
]
